# Generated by Django 4.0.5 on 2022-06-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=223)),
                ('time', models.TimeField(max_length=115)),
                ('place', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'autor',
                'db_table': 'author',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='avatar.png', upload_to='profile'),
        ),
    ]
