# Generated by Django 4.0.5 on 2022-06-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_authorization_profile_pix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authorization',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pix',
            field=models.ImageField(default='\\media\\profile\x02F9184D3-0791-4EE5-9AA8-7F485EFA2B87.jpeg', upload_to='profile'),
        ),
    ]
