# Generated by Django 4.0.5 on 2022-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_shopcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
