# Generated by Django 4.0.5 on 2022-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_shopcart_name_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='name_id',
            field=models.CharField(max_length=50),
        ),
    ]
